#!/usr/bin/env bash

#########
# Author : Shinichi Okada
# Awesome Terminal Installer
#########

version="0.2.2"
script_name=$(basename "$0")

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

usage() {
    cat <<EOF
Name: $script_name
Description: Install Homebrew, iTerm2, ZSH, Oh-My-Zsh, Starship, and plugins.

Examples:

    # Install
    ati

    # print this help
    ati -h

    # print version
    ati -v

    # Uninstall
    ati -u
EOF
    exit
}

fn_script_dir() {
    which_install=$(which "$script_name")

    if [[ -L $which_install ]]; then
        # -L file exists and is a symbolic link.
        # check if installation is Homebrew
        # if so use script_dir=/opt/homebrew/Cellar/$0/${version}/bin
        if [[ "$which_install" == *"homebrew"* ]]; then
            script_dir="$(brew --prefix)/Cellar/$0/${version}/bin"
        else
            link=$(myrealpath "${which_install}")
            script_dir=$(dirname "${link}")
        fi
    else
        script_dir="./"
    fi
    echo $script_dir
}

script_dir=$(fn_script_dir)
# echo "$script_dir"

import() {
    local file="${script_dir}/lib/${1}"
    if [ -f "${file}" ]; then
        # shellcheck disable=SC1090
        source "${file}"
    else
        bannerColor "Error: Cannot find library at: ${file}" "red" "*"
        exit 1
    fi
}

import utils
import banners

copy_plist() {
    # New check $HOME/Library/Preferences
    preferences=$HOME/Library/Preferences
    plist="com.googlecode.iterm2.plist"
    # json="Awesome-Terminal.json"
    if [[ ! -d "$preferences" ]]; then
        mkdir -p "$preferences"
    fi
    cp "$script_dir/$plist" "$preferences"
    bannerColor "iTerm2 Preferences added." "green" "*"
}

install() {
    bannerColor "Installation starting..." "magenta" "*"
    check_brew
    # check_sed
    check_iterm
    check_zsh
    check_omz
    update_zshrc_new
    check_starship
    # Snazzy color preset is in the com.googlecode.iterms2.plist
    check_firacode
    copy_plist
    add_plugins
    tput setaf 2
    cat <<'EOF'
   _                                 _____              _           _ 
  /_\__ __ _____ ___ ___ _ __  ___  |_   _|__ _ _ _ __ (_)_ _  __ _| |
 / _ \ V  V / -_|_-</ _ \ '  \/ -_)   | |/ -_) '_| '  \| | ' \/ _` | |
/_/ \_\_/\_/\___/__/\___/_|_|_\___|   |_|\___|_| |_|_|_|_|_||_\__,_|_|

is now installed!

EOF
    tput sgr0
    update_omz
}

uninstall() {
    # confirm
    read -rp "Do you want to uninstall? yes/y or no/n   " PANS

    ans=$(echo "$PANS" | cut -c 1-1 | tr "[:lower:]" "[:upper:]")
    if [[ $ans = "Y" ]]; then
        # uninstall zsh-syntax-highlighting
        bannerColor "Uninstalling zsh-syntax-highlighting..." "yellow" "*"
        "$(brew --prefix)"/bin/brew uninstall zsh-syntax-highlighting
        bannerColor "Completed uninstalling zsh-syntax-highlighting." "green" "*"

        # uninstall autojump
        bannerColor "Uninstalling autojump..." "yellow" "*"
        "$(brew --prefix)"/bin/brew uninstall autojump
        bannerColor "Completed uninstalling autojump." "green" "*"

        bannerColor "Uninstalling font-fira-code..." "yellow" "*"
        "$(brew --prefix)"/bin/brew uninstall --cask font-fira-code
        bannerColor "Completed uninstalling font-fira-code." "green" "*"

        bannerColor "Uninstalling Starship..." "yellow" "*"
        "$(brew --prefix)"/bin/brew uninstall starship
        bannerColor "Completed uninstalling Starship." "green" "*"

        bannerColor "Uninstalling Oh My Zsh..." "yellow" "*"
        sh "$HOME"/.oh-my-zsh/tools/unintall.sh
        bannerColor "Completed uninstalling ." "green" "*"

        bannerColor "Uninstalling iTerm2" "yellow" "*"
        "$(brew --prefix)"/bin/brew uninstall iterm2
        bannerColor "Completed uninstalling iTerm2." "green" "*"

        bannerColor "Uninstalling Homebrew..." "yellow" "*"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
        bannerColor "Completed uninstalling Homebrew." "green" "*"

        bannerColor "Removing ~/.oh-my-zsh" "yellow" "*"
        rm -rf "$HOME"/.oh-my-zsh
        bannerColor "Completed removing ~/.oh-my-zsh directory." "green" "*"

        # shellcheck disable=SC2016
        cat "$script_dir/zshrc_original" >"$HOME"/.zshrc_original
        bannerColor "We replaced .zshrc with the original contents." "green" "*"

        bannerColor "Uninstallation completed." "green" "*"
    else
        exit
    fi
}

fn_main() {
    if (($# == 0)); then
        install
        exit
    else
        case $1 in
        -u | --uninstall) uninstall ;;
        -h | --help) usage ;;
        -v | --version) echo "${version}" ;;
        *) usage ;;
        esac
    fi
}

fn_main "$@"
