#!/usr/bin/env bash

#########
# Author : Shinichi Okada
# Awesome Terminal Installer
#########

version="0.0.3"
script_name=$(basename "$0")

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

usage() {
    cat <<EOF
Name: $script_name
Description: Install Homebrew, iTerm2, ZSH, Oh-My-Zsh, Starship, and plugins.

Examples:

    # Install
    ati

    # print this help
    ati -h

    # print version
    ati -v

    # Uninstall
    ati -u
EOF
    exit
}

fn_script_dir() {
    which_install=$(which "$script_name")

    if [[ -L $which_install ]]; then
        # -L file exists and is a symbolic link.
        # check if installation is Homebrew
        # if so use script_dir=/opt/homebrew/Cellar/$0/${version}/bin
        if [[ "$which_install" == *"homebrew"* ]]; then
            script_dir="$(brew --prefix)/Cellar/$0/${version}/bin"
        else
            link=$(myrealpath "${which_install}")
            script_dir=$(dirname "${link}")
        fi
    else
        script_dir="./"
    fi
    echo $script_dir
}

script_dir=$(fn_script_dir)

import() {
    local file="${script_dir}/lib/${1}"
    if [ -f "${file}" ]; then
        # shellcheck disable=SC1090
        source "${file}"
    else
        echo "Error: Cannot find library at: ${file}"
        exit 1
    fi
}

import utils
import banners

copy_plist() {
    # New check $HOME/Library/Preferences
    preferences=$HOME/Library/Preferences
    plist="com.googlecode.iterm2.plist"
    # json="Awesome-Terminal.json"
    if [[ ! -d "$preferences" ]]; then
        mkdir -p "$preferences"
    fi
    cp "$script_dir/$plist" "$preferences"
    echo "iTerm2 Preferences added."
}

install() {
    echo "Installation starting ..."
    check_brew
    check_sed
    check_iterm
    check_zsh
    check_omz
    check_starship
    # Snazzy color preset is in the com.googlecode.iterms2.plist
    check_firacode
    copy_plist
    add_plugins
    cat <<'EOF'
   _                                 _____              _           _ 
  /_\__ __ _____ ___ ___ _ __  ___  |_   _|__ _ _ _ __ (_)_ _  __ _| |
 / _ \ V  V / -_|_-</ _ \ '  \/ -_)   | |/ -_) '_| '  \| | ' \/ _` | |
/_/ \_\_/\_/\___/__/\___/_|_|_\___|   |_|\___|_| |_|_|_|_|_||_\__,_|_|

is now installed!

EOF
}

uninstall() {
    # uninstall zsh-syntax-highlighting
    echo "Uninstalling zsh-syntax-highlighting"
    "$(brew --prefix)"/bin/brew uninstall zsh-syntax-highlighting
    # uninstall autojump
    echo "Uninstalling autojump..."
    "$(brew --prefix)"/bin/brew uninstall autojump
    echo "Uninstalling font-fira-code..."
    "$(brew --prefix)"/bin/brew uninstall font-fira-code
    echo "Uninstalling Starship..."
    "$(brew --prefix)"/bin/brew uninstall starship
    echo "Uninstalling Oh My Zsh..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

    echo "Uninstalling iTerm2"

    echo "Please delete the following files for complete uninstallations."
    # shellcheck disable=SC2016
    {
        echo '- eval "$(starship init zsh)" from ~/.zshrc.'
        echo "- autojump brew zsh-syntax-highlighting zsh-autosuggestions from plugins in ~/.zshrc."
        echo 'export PATH=$(brew --prefix)/bin:$PATH from ~/.zshrc.'
    }
    echo "Uninstallation completed."

}

fn_main() {
    if (($# == 0)); then
        install
        exit
    else
        case $1 in
        -u | --uninstall) uninstall ;;
        -h | --help) usage ;;
        -v | --version) echo "${version}" ;;
        *) usage ;;
        esac
    fi
}

# check_os
fn_main "$@"
