#!/usr/bin/env zsh

#########
# Author : Shinichi Okada
# Terminal Makeover Automated
#########

version="0.3.6"
script_name=$(basename "$0")

myrealpath() {
    local LINK REALPATH
    local OURPWD=$PWD
    cd "$(dirname "$1")" || exit
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")" || exit
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD" || exit
    echo "$REALPATH"
}

usage() {
    cat <<EOF
Name: $script_name
Description: Install Homebrew, iTerm2, ZSH, Oh-My-Zsh, Starship, and plugins.

Examples:

    # Install
    terma

    # Uninstall
    terma uninstall

    # print this help
    terma -h

    # print version
    terma -v

EOF
    exit
}

fn_script_dir() {
    which_install=$(which "$script_name")

    if [[ -L $which_install ]]; then
        # -L file exists and is a symbolic link.
        # check if installation is Homebrew
        # if so use script_dir=$(brew --prefix)/Cellar/$0/${version}/bin
        if [[ "$which_install" == *"homebrew"* ]]; then
            script_dir="$(brew --prefix)/Cellar/$0/${version}/bin"
        else
            link=$(myrealpath "${which_install}")
            script_dir=$(dirname "${link}")
        fi
    else
        script_dir="./"
    fi
    echo $script_dir
}

script_dir=$(fn_script_dir)
# echo "$script_dir"

import() {
    local file="${script_dir}/lib/${1}"
    if [ -f "${file}" ]; then
        # shellcheck disable=SC1090
        source "${file}"
    else
        bannerColor "Error: Cannot find library at: ${file}" "red" "*"
        exit 1
    fi
}

import utils
import banners

copy_plist() {
    # New check $HOME/Library/Preferences
    preferences=$HOME/Library/Preferences
    plist="com.googlecode.iterm2.plist"
    # json="Awesome-Terminal.json"
    if [[ ! -d "$preferences" ]]; then
        mkdir -p "$preferences"
    fi
    cp "$script_dir/$plist" "$preferences"
    bannerColor "iTerm2 Preferences added." "green" "*"
}

install() {
    bannerColor "Installation starting..." "magenta" "*"
    if [ $(uname -m) = 'arm64' ]; then
        # shellcheck disable=SC2016
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >"$HOME/.zprofile"
    fi

    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >"$HOME/.zprofile"
    fi
    echo "Updating ~/.zshrc."
    source_zshrc
    check_brew
    echo "Updating ~/.zshrc."
    source_zshrc
    # check_sed
    check_zsh
    check_omz
    # second stage
    echo "Updating ~/.zshrc."
    update_zshrc_new
    check_iterm
    check_starship
    echo "Updating ~/.zshrc."
    source_zshrc
    # Snazzy color preset is in the com.googlecode.iterms2.plist
    check_firacode
    copy_plist
    add_plugins
    echo "Updating ~/.zshrc."
    source_zshrc
    update_omz
    tput setaf 2
    cat <<'EOF'

888888888888
     88
     88
     88  ,adPPYba, 8b,dPPYba, 88,dPYba,,adPYba,  ,adPPYYba,
     88 a8P_____88 88P'   "Y8 88P'   "88"    "8a ""     `Y8
     88 8PP""""""" 88         88      88      88 ,adPPPPP88
     88 "8b,   ,aa 88         88      88      88 88,    ,88
     88  `"Ybbd8"' 88         88      88      88 `"8bbdP"Y8

is now installed!

EOF
    tput sgr0
}

uninstall() {
    # confirm
    printf '%s' 'Are you sure to uninstall? (y/n) '
    read ANS

    if [[ $ANS =~ ^[Yy]$ ]]; then
        # uninstall autojump
        bannerColor "Uninstalling autojump..." "yellow" "*"

        $(brew --prefix)/bin/brew uninstall autojump
        bannerColor "Completed uninstalling autojump." "green" "*"

        bannerColor "Uninstalling font-fira-code..." "yellow" "*"
        $(brew --prefix)/bin/brew uninstall --cask font-fira-code
        bannerColor "Completed uninstalling font-fira-code." "green" "*"

        bannerColor "Uninstalling Starship..." "yellow" "*"
        $(brew --prefix)/bin/brew uninstall starship
        bannerColor "Completed uninstalling Starship." "green" "*"

        bannerColor "Uninstalling Oh My Zsh..." "yellow" "*"
        sh "$HOME/.oh-my-zsh/tools/unintall.sh" >&/dev/null
        bannerColor "Completed uninstalling Oh-My-Zsh." "green" "*"

        bannerColor "Uninstalling iTerm2" "yellow" "*"
        $(brew --prefix)/bin/brew uninstall iterm2
        bannerColor "Completed uninstalling iTerm2." "green" "*"

        bannerColor "Uninstalling Homebrew..." "yellow" "*"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
        # bannerColor "Removing $(brew --prefix) dir..." "yellow" "*"
        # rm -rf $(brew --prefix)
        bannerColor "Completed uninstalling Homebrew." "green" "*"

        bannerColor "Removing ~/.oh-my-zsh" "yellow" "*"
        rm -rf "$HOME/.oh-my-zsh"
        bannerColor "Completed removing ~/.oh-my-zsh directory." "green" "*"

        # shellcheck disable=SC2016
        cat "$script_dir/zshrc_original" >"$HOME"/.zshrc
        bannerColor "We replaced .zshrc with the original contents." "green" "*"
        source $HOME/.zshrc

        if [ $(uname -m) = 'arm64' ]; then
            echo "Removing ~/.zprofile"
            rm "$HOME/.zprofile"
            echo "Completed removing ~/.zprofile."
        fi

        bannerColor "Uninstallation completed." "green" "*"
        bannerColor "Please close this tab, open a new tab or restart the terminal." "green" "*"
    else
        exit
    fi
}

fn_main() {
    if (($# == 0)); then
        install
        exit
    else
        case $1 in
        uninstall) uninstall ;;
        -h | --help) usage ;;
        -v | --version) echo "${version}" ;;
        *) usage ;;
        esac
    fi
}

fn_main "$@"
